export const NOTIFY_ADDING = '[NOTIFY] ADDING';
export const NOTIFY_ADDING_SUCCESS = '[NOTIFY] ADDING SUCCESS';
export const NOTIFY_ADDING_FAILED = '[NOTIFY] ADDING FAILED';
export const NOTIFY_LIST = '[NOTIFY] LIST';
export const NOTIFY_LIST_SUCCESS = '[NOTIFY] LIST_SUCCESS';
export const NOTIFY_LIST_FAILED = '[NOTIFY] LIST_FAILED';